---
title: "after_riccardo_analysis"
author: "Signe Kløve Kjær"
date: "13/5/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set working directory 

setwd("/Users/signeklovekjaer/Documents/CognitiveScience/4.semester/Social_and_cultural_dynamics_in_cognition/Exam/SocKultExam/")

#setwd("~/SocKultExam")

#load libraries
library(pacman)
p_load(lme4, lmerTest, brms, tidyverse, stringi, tm)

```


##PREPARE POOLING DATA

```{r prepare pooling data}
#read csv files with estimates
pool_estimates <- read.csv("pooling_individual_wide.csv")

#change names 
names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_answer_left'] <- 'Est_dif_blue_left_answer'

names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_answer_right'] <- 'Est_dif_blue_right_answer'

names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_correct_left'] <- 'Est_dif_blue_left_correct'

names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_correct_right'] <- 'Est_dif_blue_right_correct'


#create chosen leader column 
#create a column that sorts out all the agreed trials

pool_estimates$chosen_leader <- ifelse(pool_estimates$right_answer == pool_estimates$left_answer, "Agree", 0) 

#Create variable, which determines the chosen leader
pool_estimates$chosen_leader[pool_estimates$chosen_leader == 0 & pool_estimates$Joint_right == 0] <- "Left_lead"
pool_estimates$chosen_leader[pool_estimates$chosen_leader == 0 & pool_estimates$Joint_left == 0] <- "Right_lead"


#create column that specifies the gender of the leader
pool_estimates$Leader_gender <- 0
pool_estimates$Leader_gender <- ifelse(pool_estimates$chosen_leader == "Left_lead", as.character(pool_estimates$Gender_left), as.character(pool_estimates$Gender_right))
pool_estimates$Leader_gender[pool_estimates$chosen_leader == "Agree"] <- NA

#create column that specifies the gender of the follower
pool_estimates$Follower_gender <- 0
pool_estimates$Follower_gender <- ifelse(pool_estimates$chosen_leader == "Left_lead", as.character(pool_estimates$Gender_right), as.character(pool_estimates$Gender_left))
pool_estimates$Follower_gender[pool_estimates$chosen_leader == "Agree"] <- NA


#create stubborn leader
pool_estimates$Stubborn_leader <- 0 #Creating column of 0's

pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Right_lead" & pool_estimates$joint_answer == pool_estimates$right_answer] <- "stick" #Inserting cases were leader stick for right leader
pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Right_lead" & pool_estimates$joint_answer != pool_estimates$right_answer] <- "surrender" #Inserting cases were leader surrender for right leader

pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Left_lead" & pool_estimates$joint_answer == pool_estimates$left_answer] <- "stick" #Inserting cases were leader stick for left leader
pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Left_lead" & pool_estimates$joint_answer != pool_estimates$left_answer] <- "surrender" #Inserting cases were leader surreder for left leader

pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Agree"] <- NA #Removing cases were they agree


#code leader and follower gender as dummies, 0 = male, 1 = female
pool_estimates$Leader_gender[pool_estimates$Leader_gender == "Male"] <- 0

pool_estimates$Leader_gender[pool_estimates$Leader_gender == "Female"] <- 1

pool_estimates$Follower_gender[pool_estimates$Follower_gender == "Male"] <- 0

pool_estimates$Follower_gender[pool_estimates$Follower_gender == "Female"] <- 1



#skill dif answer
pool_estimates$skill_dif_answer <- 0
pool_estimates$skill_dif_answer <- ifelse(pool_estimates$chosen_leader == "Left_lead", pool_estimates$Est_dif_blue_left_answer/pool_estimates$Est_dif_blue_right_answer, pool_estimates$Est_dif_blue_right_answer/pool_estimates$Est_dif_blue_left_answer)

pool_estimates$skill_dif_answer[pool_estimates$chosen_leader == "Agree"] <- NA

#for correct
pool_estimates$skill_dif_correct <- 0
pool_estimates$skill_dif_correct <- ifelse(pool_estimates$chosen_leader == "Left_lead", pool_estimates$Est_dif_blue_left_correct/pool_estimates$Est_dif_blue_right_correct, pool_estimates$Est_dif_blue_right_correct/pool_estimates$Est_dif_blue_left_correct)

pool_estimates$skill_dif_correct[pool_estimates$chosen_leader == "Agree"] <- NA



#rename stubbornb leader column
names(pool_estimates)[names(pool_estimates) == 'Stubborn_leader'] <- 'Surrender'

pool_estimates$Surrender <- as.character(pool_estimates$Surrender)

#dummy code surrender columns, surrender = 1, stick = 0
pool_estimates$Surrender[pool_estimates$Surrender == "surrender"] <- 1

pool_estimates$Surrender[pool_estimates$Surrender == "stick"] <- 0

pool_estimates$Surrender[pool_estimates$chosen_leader == "Agree"] <- NA

#rename confidence
names(pool_estimates)[names(pool_estimates) == 'Response_left'] <- 'confidence_left'
names(pool_estimates)[names(pool_estimates) == 'Response_right'] <- 'confidence_right'

pool_data <- pool_estimates


#subset to left and right 
pool_left <- subset(pool_data, select = c(GroupNumber, unique_ID_left, dif_blue, dif_blue_abs, chosen_leader, Leader_gender, Follower_gender, skill_dif_correct, skill_dif_answer, confidence_left, Surrender))

pool_left$skill_dif_answer[pool_left$chosen_leader != 'Left_lead'] <- NA
pool_left$skill_dif_correct[pool_left$chosen_leader != 'Left_lead'] <- NA

pool_left$Surrender[pool_left$chosen_leader != 'Left_lead'] <- NA
pool_left$Leader_gender[pool_left$chosen_leader != 'Left_lead'] <- NA
pool_left$Follower_gender[pool_left$chosen_leader != 'Left_lead'] <- NA


pool_right <- subset(pool_data, select = c(GroupNumber, unique_ID_right, dif_blue, dif_blue_abs, chosen_leader, Leader_gender, Follower_gender, skill_dif_correct, skill_dif_answer, confidence_right, Surrender))

pool_right$skill_dif_answer[pool_right$chosen_leader != 'Right_lead'] <- NA
pool_right$skill_dif_correct[pool_right$chosen_leader != 'Right_lead'] <- NA

pool_right$Surrender[pool_right$chosen_leader != 'Right_lead'] <- NA

pool_right$Leader_gender[pool_right$chosen_leader != 'Right_lead'] <- NA
pool_right$Follower_gender[pool_right$chosen_leader != 'Right_lead'] <- NA


names(pool_left) <- c("GroupNumber", "unique_ID", "dif_blue", "dif_blue_abs", "chosen_leader", "Leader_gender", "Follower_gender", "skill_dif_correct", "skill_dif_answer", "confidence", "Surrender")


names(pool_right) <- c("GroupNumber", "unique_ID", "dif_blue", "dif_blue_abs", "chosen_leader", "Leader_gender", "Follower_gender", "skill_dif_correct", "skill_dif_answer", "confidence", "Surrender")



pool_long <- rbind(pool_left, pool_right)


pool_disagree <- na.omit(pool_long)

names(pool_disagree)[names(pool_disagree) == 'unique_ID'] <- 'Subject'


pool_disagree <- subset(pool_disagree, Subject != "14_signekirk")

#make confidence absolute 
#pool_long$Confidence <- abs(pool_long$Confidence)


#remove the groupnumber from subject name to account for within participant variation


pool_disagree$Subject <- as.character(pool_disagree$Subject)
pool_disagree$Subject <- tolower(pool_disagree$Subject)

pool_disagree$Subject <- str_extract(pool_disagree$Subject,"[a-z]+")

```


#MODELS
```{r run the answer model}

#get priors
get_prior(Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ), data = pool_disagree, family = "bernoulli")


prior_answer <- c(
  prior(normal(0,1),class="Intercept"),
  prior(normal(0,.2),class="b"),
  prior(normal(0,.1),class="sd")
)


#prior predictive check pool
prior_check_answer <- brm(Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ), prior = prior_answer, data = pool_disagree, sample_prior = "only",iter = 4000, family = "bernoulli", chains = 2, cores = 2)

pp_check(prior_check_answer, nsamples = 100)


# Model w skill difference
m_answer <- brm(
  Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ),
  data = pool_disagree,
  prior = prior_answer,
  sample_prior=T,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123, # Adding a seed makes results reproducible.
  cores=2,
  chains=2,
  control = list(adapt_delta = 0.9) #only for answer model, due to Eff.Sample
) 


summary(m_answer)


```


```{r run the model with correct}

#get priors
get_prior(Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ), data = pool_disagree, family = "bernoulli")


prior_correct <- c(
  prior(normal(0,1),class="Intercept"),
  prior(normal(0,.2),class="b"),
  prior(normal(0,.1),class="sd")
)

#prior predictive check pool
prior_check_correct <- brm(Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ), prior = prior_correct, data = pool_disagree, sample_prior = "only",iter = 4000, family = "bernoulli", chains = 2, cores = 2)

pp_check(prior_check_correct, nsamples = 100)

# Model w skill difference
m_correct <- brm(
  Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ),
  data = pool_disagree,
  prior = prior_correct,
  sample_prior=T,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123, # Adding a seed makes results reproducible.
  cores=2,
  chains=2
) 

summary(m_correct)

```



```{r model without skill difference}

prior_0 <- c(
  prior(normal(0,.2),class="b"),
  prior(normal(0,.1),class="sd")
)

#prior predictive check pool
prior_check_0 <- brm(Surrender ~ 0 + Leader_gender : Follower_gender + (0 + Follower_gender | Subject ), prior = prior_0, data = pool_disagree, sample_prior = "only",iter = 4000, family = "bernoulli", chains = 2, cores = 2)

pp_check(prior_check_0, nsamples = 100)

#model without skill difference, correct
m_0 <- brm(
  Surrender ~ 0 + Leader_gender : Follower_gender + (0 + Follower_gender | Subject ),
  data = pool_disagree,
  prior = prior_0,
  sample_prior=T,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123, # Adding a seed makes results reproducible.
  chains=2,
  cores=2
) 
  
marginal_effects(m_0)

```



#MODEL COMPARISON

```{r answer and correct}
waic(m_answer, m_correct)

```

```{r all}
waic(m_correct, m_answer, m_0)

compare(m_correct, m_answer)

waic(m_answer, m_0)


marginal_effects(m_answer)

marginal_effects(m_0)

marginal_effects(m_correct)

4+4

```



#### #### #### #### #### #### HYPOTHESIS TESTING #### #### #### #### #### #### 



# H1: there is a leader effect: male leaders tend to surrender less than female leaders
```{r H1: there is a leader effect: male leaders tend to surrender less than female leaders}
#hypothesis

hypothesis(m_0, "(Leader_gender0:Follower_gender0 + Leader_gender0:Follower_gender1)/2 < (Leader_gender1:Follower_gender0 + Leader_gender1:Follower_gender1)/2")



```

# H1: plotting
```{r}




```




#H2: there is a follower effect: leaders tend to surrender more to men than to women
```{r H2: there is a follower effect: leaders tend to surrender more to men than to women }

# H2: there is a follower effect: leaders tend to surrender more to men than to women


hypothesis(m_0, "(Leader_gender0:Follower_gender0 + Leader_gender1:Follower_gender0)/2 > (Leader_gender0:Follower_gender1 + Leader_gender1:Follower_gender1)/2")




```

# H2: plotting
```{r}

```


```{r H3: there is an interaction, males are more discriminative as to their followers gender than females are }
# H3: there is an interaction: males are more discriminative as to their followers gender than females are


hypothesis(m_0, "(Leader_gender0:Follower_gender0 - Leader_gender0:Follower_gender1) > (Leader_gender1:Follower_gender0 - Leader_gender1:Follower_gender1)")





```


# H3: plotting
```{r}

```








