---
title: "Signe1_Analysis"
author: "Signe Kløve Kjær"
date: "10/5/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set working directory 

setwd("/Users/signeklovekjaer/Documents/CognitiveScience/4.semester/Social_and_cultural_dynamics_in_cognition/Exam/SocKultExam/")

#setwd("~/SocKultExam")


library(pacman)
p_load(lme4, lmerTest, brms, tidyverse)

```



## PREPARE NO POOLING 


```{r prepare csv data files }
#load no pooling csv files 

left <- read.csv("Results_left.csv")

right <- read.csv("Results_left_and_right.csv")

joint <- read.csv("Results_left_right_joint.csv")


#change column names 
names(joint)[names(joint) == 'Est_dif_blue_joint'] <- 'Est_dif_blue_joint_answer'
names(left)[names(left) == 'Est_dif_blue_left'] <- 'Est_dif_blue_left_answer'
names(right)[names(right) == 'Est_dif_blue_right'] <- 'Est_dif_blue_right_answer'


#delete columns which we do not need for the analysis
left_ontheway <- select(left, -c(53:59, "Error_int_left_correct", "Est_int_left_correct", "Est_int_left", "Error_int_left", "Error_dif_blue_left"))


#merge the shit 
no_pool_data <- cbind(left_ontheway, right$Est_dif_blue_right_answer, right$Est_dif_blue_right_correct, joint$Est_dif_blue_joint_answer, joint$Est_dif_blue_joint_correct)


#rename column names
names(no_pool_data)[names(no_pool_data) == 'joint$Est_dif_blue_joint_answer'] <- 'Est_dif_blue_joint_answer'

names(no_pool_data)[names(no_pool_data) == 'joint$Est_dif_blue_joint_correct'] <- 'Est_dif_blue_joint_correct'


names(no_pool_data)[names(no_pool_data) == 'right$Est_dif_blue_right_answer'] <- 'Est_dif_blue_right_answer'

names(no_pool_data)[names(no_pool_data) == 'right$Est_dif_blue_right_correct'] <- 'Est_dif_blue_right_correct'


#take one row for each group 
#no_pool_data <- no_pool_data[!duplicated(no_pool_data$GroupNumber), ]

```


```{r compute skill_dif and dummy code leader follower gender}

#change to character 
no_pool_data$Leader_gender <- as.character(no_pool_data$Leader_gender)
no_pool_data$Follower_gender <- as.character(no_pool_data$Follower_gender)


#code leader and follower gender as dummies, 0 = male, 1 = female
no_pool_data$Leader_gender[no_pool_data$Leader_gender == "Male"] <- 0

no_pool_data$Leader_gender[no_pool_data$Leader_gender == "Female"] <- 1

no_pool_data$Follower_gender[no_pool_data$Follower_gender == "Male"] <- 0

no_pool_data$Follower_gender[no_pool_data$Follower_gender == "Female"] <- 1

#compute skill_difference (my slope divided by my partners slope)
#for answer
no_pool_data$skill_dif_answer <- 0
no_pool_data$skill_dif_answer <- ifelse(no_pool_data$chosen_leader == "Left_lead", no_pool_data$Est_dif_blue_left_answer/no_pool_data$Est_dif_blue_right_answer, no_pool_data$Est_dif_blue_right_answer/no_pool_data$Est_dif_blue_left_answer)
no_pool_data$skill_dif_answer[no_pool_data$chosen_leader == "Agree"] <- NA

#for correct
no_pool_data$skill_dif_correct <- 0
no_pool_data$skill_dif_correct <- ifelse(no_pool_data$chosen_leader == "Left_lead", no_pool_data$Est_dif_blue_left_correct/no_pool_data$Est_dif_blue_right_correct, no_pool_data$Est_dif_blue_right_correct/no_pool_data$Est_dif_blue_left_correct)
no_pool_data$skill_dif_correct[no_pool_data$chosen_leader == "Agree"] <- NA


#rename stubbornb leader column
names(no_pool_data)[names(no_pool_data) == 'Stubborn_leader'] <- 'Surrender'

no_pool_data$Surrender <- as.character(no_pool_data$Surrender)

#dummy code surrender columns, surrender = 1, stick = 0
no_pool_data$Surrender[no_pool_data$Surrender == "surrender"] <- 1

no_pool_data$Surrender[no_pool_data$Surrender == "stick"] <- 0

no_pool_data$Surrender[no_pool_data$chosen_leader == "Agree"] <- NA

#Making column specifying the leader and follower gender
# no_pool_data$Leader_Follower <- paste("Leader:", no_pool_data$Leader_gender, "_Follower:", no_pool_data$Follower_gender, sep = "")
# no_pool_data$Leader_Follower[no_pool_data$chosen_leader == "Agree"] <- NA


#rename confidence
names(no_pool_data)[names(no_pool_data) == 'Response_left'] <- 'confidence_left'
names(no_pool_data)[names(no_pool_data) == 'Response_right'] <- 'confidence_right'





```





```{r create long form}
#subset to left and right 
no_pool_left <- subset(no_pool_data, select = c(GroupNumber, unique_ID_left, dif_blue, dif_blue_abs, chosen_leader, Leader_gender, Follower_gender, skill_dif_correct, skill_dif_answer, confidence_left, Surrender))

no_pool_left$skill_dif_answer[no_pool_left$chosen_leader != 'Left_lead'] <- NA
no_pool_left$skill_dif_correct[no_pool_left$chosen_leader != 'Left_lead'] <- NA

no_pool_left$Surrender[no_pool_left$chosen_leader != 'Left_lead'] <- NA
no_pool_left$Leader_gender[no_pool_left$chosen_leader != 'Left_lead'] <- NA
no_pool_left$Follower_gender[no_pool_left$chosen_leader != 'Left_lead'] <- NA


no_pool_right <- subset(no_pool_data, select = c(GroupNumber, unique_ID_right, dif_blue, dif_blue_abs, chosen_leader, Leader_gender, Follower_gender, skill_dif_correct, skill_dif_answer, confidence_right, Surrender))

no_pool_right$skill_dif_answer[no_pool_right$chosen_leader != 'Right_lead'] <- NA
no_pool_right$skill_dif_correct[no_pool_right$chosen_leader != 'Right_lead'] <- NA

no_pool_right$Surrender[no_pool_right$chosen_leader != 'Right_lead'] <- NA

no_pool_right$Leader_gender[no_pool_right$chosen_leader != 'Right_lead'] <- NA
no_pool_right$Follower_gender[no_pool_right$chosen_leader != 'Right_lead'] <- NA


names(no_pool_left) <- c("GroupNumber", "unique_ID", "dif_blue", "dif_blue_abs", "chosen_leader", "Leader_gender", "Follower_gender", "skill_dif_correct", "skill_dif_answer", "confidence", "Surrender")


names(no_pool_right) <- c("GroupNumber", "unique_ID", "dif_blue", "dif_blue_abs", "chosen_leader", "Leader_gender", "Follower_gender", "skill_dif_correct", "skill_dif_answer", "confidence", "Surrender")




no_pool_long <- rbind(no_pool_left, no_pool_right)

no_pool_disagree <- na.omit(no_pool_long)

names(no_pool_disagree)[names(no_pool_disagree) == 'unique_ID'] <- 'Subject'

#make confidence absolute 
#no_pool_long$Confidence <- abs(no_pool_long$Confidence)
```


##PREPARE POOLING DATA

```{r}
#read csv files with estimates
pool_estimates <- read.csv("pooling_individual_wide.csv")

#change names 
names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_answer_left'] <- 'Est_dif_blue_left_answer'

names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_answer_right'] <- 'Est_dif_blue_right_answer'

names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_correct_left'] <- 'Est_dif_blue_left_correct'

names(pool_estimates)[names(pool_estimates) == 'Slope_ranef_fixef_estimate_correct_right'] <- 'Est_dif_blue_right_correct'


#create chosen leader column 
#create a column that sorts out all the agreed trials

pool_estimates$chosen_leader <- ifelse(pool_estimates$right_answer == pool_estimates$left_answer, "Agree", 0) 

#Create variable, which determines the chosen leader
pool_estimates$chosen_leader[pool_estimates$chosen_leader == 0 & pool_estimates$Joint_right == 0] <- "Left_lead"
pool_estimates$chosen_leader[pool_estimates$chosen_leader == 0 & pool_estimates$Joint_left == 0] <- "Right_lead"


#create column that specifies the gender of the leader
pool_estimates$Leader_gender <- 0
pool_estimates$Leader_gender <- ifelse(pool_estimates$chosen_leader == "Left_lead", as.character(pool_estimates$Gender_left), as.character(pool_estimates$Gender_right))
pool_estimates$Leader_gender[pool_estimates$chosen_leader == "Agree"] <- NA

#create column that specifies the gender of the follower
pool_estimates$Follower_gender <- 0
pool_estimates$Follower_gender <- ifelse(pool_estimates$chosen_leader == "Left_lead", as.character(pool_estimates$Gender_right), as.character(pool_estimates$Gender_left))
pool_estimates$Follower_gender[pool_estimates$chosen_leader == "Agree"] <- NA


#create stubborn leader
pool_estimates$Stubborn_leader <- 0 #Creating column of 0's

pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Right_lead" & pool_estimates$joint_answer == pool_estimates$right_answer] <- "stick" #Inserting cases were leader stick for right leader
pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Right_lead" & pool_estimates$joint_answer != pool_estimates$right_answer] <- "surrender" #Inserting cases were leader surrender for right leader

pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Left_lead" & pool_estimates$joint_answer == pool_estimates$left_answer] <- "stick" #Inserting cases were leader stick for left leader
pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Left_lead" & pool_estimates$joint_answer != pool_estimates$left_answer] <- "surrender" #Inserting cases were leader surreder for left leader

pool_estimates$Stubborn_leader[pool_estimates$chosen_leader == "Agree"] <- NA #Removing cases were they agree


#code leader and follower gender as dummies, 0 = male, 1 = female
pool_estimates$Leader_gender[pool_estimates$Leader_gender == "Male"] <- 0

pool_estimates$Leader_gender[pool_estimates$Leader_gender == "Female"] <- 1

pool_estimates$Follower_gender[pool_estimates$Follower_gender == "Male"] <- 0

pool_estimates$Follower_gender[pool_estimates$Follower_gender == "Female"] <- 1



#skill dif answer
pool_estimates$skill_dif_answer <- 0
pool_estimates$skill_dif_answer <- ifelse(pool_estimates$chosen_leader == "Left_lead", pool_estimates$Est_dif_blue_left_answer/pool_estimates$Est_dif_blue_right_answer, pool_estimates$Est_dif_blue_right_answer/pool_estimates$Est_dif_blue_left_answer)

pool_estimates$skill_dif_answer[pool_estimates$chosen_leader == "Agree"] <- NA

#for correct
pool_estimates$skill_dif_correct <- 0
pool_estimates$skill_dif_correct <- ifelse(pool_estimates$chosen_leader == "Left_lead", pool_estimates$Est_dif_blue_left_correct/pool_estimates$Est_dif_blue_right_correct, pool_estimates$Est_dif_blue_right_correct/pool_estimates$Est_dif_blue_left_correct)

pool_estimates$skill_dif_correct[pool_estimates$chosen_leader == "Agree"] <- NA



#rename stubbornb leader column
names(pool_estimates)[names(pool_estimates) == 'Stubborn_leader'] <- 'Surrender'

pool_estimates$Surrender <- as.character(pool_estimates$Surrender)

#dummy code surrender columns, surrender = 1, stick = 0
pool_estimates$Surrender[pool_estimates$Surrender == "surrender"] <- 1

pool_estimates$Surrender[pool_estimates$Surrender == "stick"] <- 0

pool_estimates$Surrender[pool_estimates$chosen_leader == "Agree"] <- NA

#rename confidence
names(pool_estimates)[names(pool_estimates) == 'Response_left'] <- 'confidence_left'
names(pool_estimates)[names(pool_estimates) == 'Response_right'] <- 'confidence_right'

pool_data <- pool_estimates


#subset to left and right 
pool_left <- subset(pool_data, select = c(GroupNumber, unique_ID_left, dif_blue, dif_blue_abs, chosen_leader, Leader_gender, Follower_gender, skill_dif_correct, skill_dif_answer, confidence_left, Surrender))

pool_left$skill_dif_answer[pool_left$chosen_leader != 'Left_lead'] <- NA
pool_left$skill_dif_correct[pool_left$chosen_leader != 'Left_lead'] <- NA

pool_left$Surrender[pool_left$chosen_leader != 'Left_lead'] <- NA
pool_left$Leader_gender[pool_left$chosen_leader != 'Left_lead'] <- NA
pool_left$Follower_gender[pool_left$chosen_leader != 'Left_lead'] <- NA


pool_right <- subset(pool_data, select = c(GroupNumber, unique_ID_right, dif_blue, dif_blue_abs, chosen_leader, Leader_gender, Follower_gender, skill_dif_correct, skill_dif_answer, confidence_right, Surrender))

pool_right$skill_dif_answer[pool_right$chosen_leader != 'Right_lead'] <- NA
pool_right$skill_dif_correct[pool_right$chosen_leader != 'Right_lead'] <- NA

pool_right$Surrender[pool_right$chosen_leader != 'Right_lead'] <- NA

pool_right$Leader_gender[pool_right$chosen_leader != 'Right_lead'] <- NA
pool_right$Follower_gender[pool_right$chosen_leader != 'Right_lead'] <- NA


names(pool_left) <- c("GroupNumber", "unique_ID", "dif_blue", "dif_blue_abs", "chosen_leader", "Leader_gender", "Follower_gender", "skill_dif_correct", "skill_dif_answer", "confidence", "Surrender")


names(pool_right) <- c("GroupNumber", "unique_ID", "dif_blue", "dif_blue_abs", "chosen_leader", "Leader_gender", "Follower_gender", "skill_dif_correct", "skill_dif_answer", "confidence", "Surrender")



pool_long <- rbind(pool_left, pool_right)


pool_disagree <- na.omit(pool_long)

names(pool_disagree)[names(pool_disagree) == 'unique_ID'] <- 'Subject'

#make confidence absolute 
#pool_long$Confidence <- abs(pool_long$Confidence)




```

####STOPPPPPPEEEEEEE§

```{r create the answer model with main effects }
#####MAKE THE MODEL########

# Propensity to surrender ~ skill_difference * leader_gender * follower_gender + (1 + skill_difference:followergender|ID)
# 
# 
# Propensity to surrender ~ skill_difference * leader_gender * follower_gender + confidence * leader_gender * follower_gender + (1 + skill_difference:followergender|ID)

get_prior(Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ), data = no_pool_long, family = "bernoulli")


#Defining priors
prior_answer =  c(
  prior(normal(0,1), class = "b", coef = "Follower_gender1"),
  prior(normal(0,1), class = "b", coef = "Leader_gender1"),
  prior(normal(0,1), class = "b", coef = "Leader_gender1:Follower_gender1"),
  prior(normal(0,1), class = "b", coef = "skill_dif_answer"),
  prior(normal(0,1), class = "b", coef = "skill_dif_answer:Follower_gender1"),
  prior(normal(0,1), class = "b", coef = "skill_dif_answer:Leader_gender1"),
  prior(normal(0,1), class = "b", coef = "skill_dif_answer:Leader_gender1:Follower_gender1"),
  prior(normal(0,1), class = "Intercept"), 
  prior(normal(0,1), class = "sd", coef = "Intercept", group = "Subject"),
  prior(normal(0,1), class = "sd", coef = "skill_dif_answer:Follower_gender0", group = "Subject"),
  prior(normal(0,1), class = "sd", coef = "skill_dif_answer:Follower_gender1", group = "Subject")
  )

#prior predictive check no pool
prior_check_no_pool_answer <- brm(Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ), prior = prior_answer, data = no_pool_disagree, sample_prior = "only",iter = 4000, family = "bernoulli")

#prior predictive check pool
prior_check_pool_answer <- brm(Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ), prior = prior_answer, data = pool_disagree, sample_prior = "only",iter = 4000, family = "bernoulli")



pp_check(prior_check_no_pool_answer, nsamples = 100)

pp_check(prior_check_pool_answer, nsamples = 100)


m_no_pool_answer <- brm(
  Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ),
  data = no_pool_disagree,
  prior = prior_answer,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123 # Adding a seed makes results reproducible.
  
  ) 


m_pool_answer <- brm(
  Surrender ~ skill_dif_answer * Leader_gender * Follower_gender + (1 + skill_dif_answer:Follower_gender | Subject ),
  data = pool_disagree,
  prior = prior_answer,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123 # Adding a seed makes results reproducible.
  
  ) 

summary(m_pool_answer)


```

```{r}
conditions <- make_conditions(m_pool_correct, "skill_dif_correct")
wuu <- marginal_effects(m_pool_correct, "Leader_gender:Follower_gender", conditions = conditions, select_points = 0.1)

plot(wuu)


dens(pool_disagree$skill_dif_answer)
```


```{r create the correct model with main effects }

get_prior(Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ), data = no_pool_disagree, family = "bernoulli")

get_prior(Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ), data = pool_disagree, family = "bernoulli")



#Defining priors
prior_correct =  c(
  prior(normal(0,1), class = "b", coef = "Follower_gender1"),
  prior(normal(0,1), class = "b", coef = "Leader_gender1"),
  prior(normal(0,1), class = "b", coef = "Leader_gender1:Follower_gender1"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct:Follower_gender1"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct:Leader_gender1"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct:Leader_gender1:Follower_gender1"),
  prior(normal(0,1), class = "Intercept"), 
  prior(normal(0,1), class = "sd", coef = "Intercept", group = "Subject"),
  prior(normal(0,1), class = "sd", coef = "skill_dif_correct:Follower_gender0", group = "Subject"),
  prior(normal(0,1), class = "sd", coef = "skill_dif_correct:Follower_gender1", group = "Subject")
  )


#prior predictive check no pool
prior_check_no_pool_correct <- brm(Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ), prior = prior_correct, data = no_pool_disagree, sample_prior = "only",iter = 4000, family = "bernoulli")

#prior predictive check pool
prior_check_pool_correct <- brm(Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ), prior = prior_correct, data = pool_disagree, sample_prior = "only",iter = 4000, family = "bernoulli")



pp_check(prior_check_no_pool_correct, nsamples = 100)

pp_check(prior_check_pool_correct, nsamples = 100)


m_no_pool_correct <- brm(
  Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ),
  data = no_pool_disagree,
  prior = prior_correct,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123 # Adding a seed makes results reproducible.
  
  ) 


pool_disagree$Surrender <- as.factor(pool_disagree$Surrender)
pool_disagree$Leader_gender <- as.factor(pool_disagree$Leader_gender)
pool_disagree$Follower_gender <- as.factor(pool_disagree$Follower_gender)

#pool_disagree$skill_dif_correct_z <- scale(pool_disagree$skill_dif_correct)

# prior_correct_z =  c(
#   prior(normal(0,1), class = "b", coef = "Follower_gender1"),
#   prior(normal(0,1), class = "b", coef = "Leader_gender1"),
#   prior(normal(0,1), class = "b", coef = "Leader_gender1:Follower_gender1"),
#   prior(normal(0,1), class = "b", coef = "skill_dif_correct_z"),
#   prior(normal(0,1), class = "b", coef = "skill_dif_correct_z:Follower_gender1"),
#   prior(normal(0,1), class = "b", coef = "skill_dif_correct_z:Leader_gender1"),
#   prior(normal(0,1), class = "b", coef = "skill_dif_correct_z:Leader_gender1:Follower_gender1"),
#   prior(normal(0,1), class = "Intercept"), 
#   prior(normal(0,1), class = "sd", coef = "Intercept", group = "Subject"),
#   prior(normal(0,1), class = "sd", coef = "skill_dif_correct_z:Follower_gender0", group = "Subject"),
#   prior(normal(0,1), class = "sd", coef = "skill_dif_correct_z:Follower_gender1", group = "Subject")
#   )
# 
# m_pool_correct_z <- brm(
#   Surrender ~ skill_dif_correct_z * Leader_gender * Follower_gender + (1 + skill_dif_correct_z:Follower_gender | Subject ),
#   data = pool_disagree,
#   prior = prior_correct_z,
#   family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
#   seed = 123 # Adding a seed makes results reproducible.
#   
#   ) 

#why such a big difference between effective samples?
summary(m_pool_correct)

summary(m_pool_answer)

```



#THEA TRIES SOMETHING NEW

```{r}

pool_disagree$Leader_Follower <- paste("Leader:", pool_disagree$Leader_gender, "_Follower:", pool_disagree$Follower_gender, sep = "")


pool_disagree$Leader_Follower[pool_disagree$Leader_Follower == "Leader:0_Follower:0"] <- "1"

pool_disagree$Leader_Follower[pool_disagree$Leader_Follower == "Leader:1_Follower:1"] <- "2"

pool_disagree$Leader_Follower[pool_disagree$Leader_Follower == "Leader:1_Follower:0"] <- "3"

pool_disagree$Leader_Follower[pool_disagree$Leader_Follower == "Leader:0_Follower:1"] <- "4"



get_prior(Surrender ~ skill_dif_correct * Leader_Follower + (1 + skill_dif_correct:Follower_gender | Subject ), data = pool_disagree, family = "bernoulli")

#Defining priors
prior_correct_thea =  c(
  prior(normal(0,1), class = "b", coef = "Leader_Follower2"),
  prior(normal(0,1), class = "b", coef = "Leader_Follower3"),
  prior(normal(0,1), class = "b", coef = "Leader_Follower4"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct:Leader_Follower2"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct:Leader_Follower3"),
  prior(normal(0,1), class = "b", coef = "skill_dif_correct:Leader_Follower4"),
  prior(normal(0,1), class = "Intercept"), 
  prior(normal(0,1), class = "sd", coef = "Intercept", group = "Subject"),
  prior(normal(0,1), class = "sd", coef = "skill_dif_correct:Follower_gender0", group = "Subject"),
  prior(normal(0,1), class = "sd", coef = "skill_dif_correct:Follower_gender1", group = "Subject")
  )


thea_m_pool_correct <- brm(
  Surrender ~ skill_dif_correct * Leader_Follower + (1 + skill_dif_correct:Follower_gender | Subject ),
  data = pool_disagree,
  prior = prior_correct_thea,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123 # Adding a seed makes results reproducible.
  
  ) 


summary(thea_m_pool_correct)

conditions <- make_conditions(thea_m_pool_correct, "skill_dif_correct")

conditions$cond__ <- c("1","2","3")

hey <- marginal_effects(thea_m_pool_correct, "skill_dif_correct:Leader_Follower")
hey1 <- marginal_effects(thea_m_pool_correct, "Leader_Follower")

marginal_effects(thea_m_pool_correct)
```


##lets look at some plots!!!!

```{r plot with data, confidence intervals and errorbars}

#look away from outliers
low <- quantile(pool_disagree$skill_dif_correct, probs = 0.05)
high <- quantile(pool_disagree$skill_dif_correct, probs = 0.95)

#create newdata to make predictions from 
nd <- 
  expand.grid(tibble(skill_dif_correct= c(low, high) %>% 
           rep(., times = 3),
         Follower_gender=factor(0:1) %>% rep(., times = 3),
         Leader_gender = factor(0:1) %>% rep(., times = 3),
         Subject = NA))

#predict probabilities for surrender, use fitted to get upper and lower quantile measures in probabilities
pred_pool_correct <-
  fitted(m_pool_correct, newdata = nd, re_formula = NULL) %>%  # we can use the same nd data from last time
  as_tibble() %>%
  bind_cols(nd) #%>%
  #mutate(Leader_gender = ifelse(Leader_gender == 1, "Female", "Male"))

#pool_disagree$Surrender <- as.numeric(pool_disagree$Surrender)

# plotting the fitted regression lines
ggplot(pred_pool_correct, aes(x = skill_dif_correct, y = Estimate, group = Leader_gender, col = Leader_gender)) +
  geom_line() +
  facet_grid(. ~ Follower_gender) + 
  geom_point(data=pool_disagree, aes(x=skill_dif_correct,y=Surrender,color=Leader_gender)) + 
  xlim(low, high) +
  facet_grid(.~ Follower_gender) +
  geom_smooth(data = pred_pool_correct, aes(y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = Leader_gender),stat = "identity", alpha = 1/4, size = 1/2) + facet_grid(.~ Follower_gender) + 
  geom_errorbar(data = pred_pool_correct, aes(y = Estimate, ymin = (Estimate-Est.Error), ymax = (Estimate + Est.Error), fill = Leader_gender),stat = "identity", alpha = 2/4, size = 1/2) + facet_grid(.~ Follower_gender)
  



ggplot(pred_pool_correct, aes(x = skill_dif_correct, y = Estimate, group = Leader_gender, col = Leader_gender)) +
  geom_line() +
  facet_grid(. ~ Follower_gender)


conditions <- make_conditions(m_pool_correct, "skill_dif_correct")
conditions$cond__ <- as.character(conditions$skill_dif_correct)
wuu <- marginal_effects(m_pool_correct, "Leader_gender:Follower_gender", conditions = conditions, select_points = 0.1)

plot(wuu)

marginal_effects(m_pool_correct)

```


```{r for answer}

#look away from outliers
low <- quantile(pool_disagree$skill_dif_answer, probs = 0.05)
high <- quantile(pool_disagree$skill_dif_answer, probs = 0.95)

#create newdata to make predictions from 
nd <- 
  expand.grid(tibble(skill_dif_answer= c(low, high) %>% 
           rep(., times = 3),
         Follower_gender=factor(0:1) %>% rep(., times = 3),
         Leader_gender = factor(0:1) %>% rep(., times = 3),
         Subject = NA))

#predict probabilities for surrender, use fitted to get upper and lower quantile measures in probabilities
pred_pool_answer <-
  fitted(m_pool_answer, newdata = nd, re_formula = NULL) %>%  # we can use the same nd data from last time
  as_tibble() %>%
  bind_cols(nd) #%>%
  #mutate(Leader_gender = ifelse(Leader_gender == 1, "Female", "Male"))

#pool_disagree$Surrender <- as.numeric(pool_disagree$Surrender)

# plotting the fitted regression lines
ggplot(pred_pool_answer, aes(x = skill_dif_answer, y = Estimate, group = Leader_gender, col = Leader_gender)) +
  geom_line() +
  facet_grid(. ~ Follower_gender) + 
  geom_point(data=pool_disagree, aes(x=skill_dif_answer,y=Surrender,color=Leader_gender)) + 
  xlim(low, high) +
  facet_grid(.~ Follower_gender) +
  geom_smooth(data = pred_pool_answer, aes(y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = Leader_gender),stat = "identity", alpha = 1/4, size = 1/2) + facet_grid(.~ Follower_gender) + 
  geom_errorbar(data = pred_pool_answer, aes(y = Estimate, ymin = (Estimate-Est.Error), ymax = (Estimate + Est.Error), fill = Leader_gender),stat = "identity", alpha = 2/4, size = 1/2) + facet_grid(.~ Follower_gender)
  



ggplot(pred_pool_answer, aes(x = skill_dif_answer, y = Estimate, group = Leader_gender, col = Leader_gender)) +
  geom_line() +
  facet_grid(. ~ Follower_gender)


conditions <- make_conditions(m_pool_answer, "skill_dif_answer")
conditions$cond__ <- as.character(conditions$skill_dif_answer)
wuu <- marginal_effects(m_pool_answer, "Leader_gender:Follower_gender", conditions = conditions, select_points = 0.1)

plot(wuu)

marginal_effects(m_pool_answer)



```



```{r marginal effects plot}

conditions <- make_conditions(m_pool_correct, "skill_dif_correct")
conditions$cond__ <- as.character(conditions$skill_dif_correct)

marginal_effects(m_pool_correct,"Leader_gender:Follower_gender", conditions = conditions)


```

```{r theas plot}

# 1: FF
# 2: MM
# 3: FM
# 4: MF

#effect of skill_dif
marginal_effects(thea_m_pool_correct, "skill_dif_correct:Leader_Follower")

#how many times will there be a "surrender" in each condition 
marginal_effects(thea_m_pool_correct, "Leader_Follower")

```




#PLOT




```{r}

pool_disagree$Leader_Follower <- paste("Leader:", pool_disagree$Leader_gender, "_Follower:", pool_disagree$Follower_gender, sep = "")

pool_disagree$Leader_Follower <- as.numeric(pool_disagree$Leader_Follower)
pool_disagree$Leader_Follower <- as.factor(pool_disagree$Leader_Follower)



nd <- 
  expand.grid(tibble(skill_dif_correct= c(min(pool_disagree$skill_dif_correct),1,max(pool_disagree$skill_dif_correct)) %>% 
           rep(., times = 2),
         Follower_gender=factor(0:1) %>% rep(., times = 3),
         Leader_gender = factor(0:1) %>% rep(., times = 3),
         Subject = NA))

nd <- 
  tibble(skill_dif_correct= c(min(pool_disagree$skill_dif_correct),max(pool_disagree$skill_dif_correct)), Follower_gender=factor(0:1), Leader_gender = factor(0:1) ,Subject = NA) 


pred_pool_correct <-
  fitted(m_pool_correct, newdata = nd, re_formula = NULL) %>%  # we can use the same nd data from last time
  as_tibble() %>%
  bind_cols(nd) #%>%
#  mutate(Leader_gender = ifelse(Leader_gender == 1, "Female", "Male"))
  

# plotting the fitted regression lines
ggplot(pred_pool_correct, aes(x = skill_dif_correct, y = Estimate, group = Leader_gender, col = Leader_gender)) + 
geom_line() + 
facet_grid(. ~ Follower_gender)



pred_pool_correct <- as.data.frame(pred_pool_correct)

dd %>%
  mutate(cont_africa = ifelse(cont_africa == 1, "Africa", "not Africa")) %>%
  
  ggplot(aes(x = rugged, color = cont_africa)) +
  geom_smooth(data = f,
              aes(y = Estimate, ymin = Q2.5, ymax = Q97.5,
                  fill = cont_africa),
              stat = "identity", 
              alpha = 1/4, size = 1/2) +
  geom_point(aes(y = log_gdp),
             size = 2/3) +
  scale_colour_pander() +
  scale_fill_pander() +
  scale_x_continuous("Terrain Ruggedness Index", expand = c(0, 0)) +
  ylab("log GDP from year 2000") +
  theme_pander() + 
  theme(text = element_text(family = "Times"),
        legend.position = "none") +
  facet_wrap(~cont_africa)


#new try

#We will split up the interpretation of such model in two parts: (i) interpret the intercept (when X1 = 0) and (ii) interpret the slopes, the effect of X1 on y.


test <- expand.grid(skill_dif_correct = c(min(pool_disagree$skill_dif_correct),1,max(pool_disagree$skill_dif_correct)), 
            Follower_gender = factor(0:1),
            Leader_gender = factor(0:1), 
            Subject = NA,
            Surrender = NA %>% rep(., times = 100))


test$Surrender <- predict(m_pool_correct, newdata = test, re_formula = NULL)


pred <- expand.grid(skill_dif_correct = c(min(pool_disagree$skill_dif_correct),1,max(pool_disagree$skill_dif_correct)),Follower_gender=factor(0:1),Leader_gender=factor(0:1),Surrender = NA,  Subject = NA)

pred$Surrender <- predict(m_pool_correct,pred, re_formula = NULL)

pred <- subset(pred, select = -c(Subject))

#understanding the estimates: the intercepts
ggplot(pool_disagree,aes(x=skill_dif_correct,y=Surrender,color=Follower_gender))+geom_point()+
facet_grid(.~Leader_gender,labeller = "label_both")+
stat_smooth(method="lm",se=FALSE) + geom_linerange(data=pred[c(2,5),],
size=2,color="orange") +
#geom_text(data=pred[2,],aes(label="F12"),vjust=4,color="black")+
geom_linerange(data=pred[c(8,11),],
size=2,color="orange")  +
#geom_text(data=pred[8,],aes(label="F12+\nF12:F22"),vjust=2,color="black") #+
geom_point(data=pred[pred$X==0,],color="black")



#understanding the estimates: the intercepts
ggplot(pool_disagree,aes(x=skill_dif_correct,y=Surrender,color=Follower_gender))+geom_point()+
facet_grid(.~Leader_gender,labeller = "label_both")+
stat_smooth(method="lm",se=FALSE) + geom_linerange(data=pred[c(2,5),],aes(ymin=Surrender[1],ymax=Surrender[2]),
size=2,color="orange") +
#geom_text(data=pred[2,],aes(label="F12"),vjust=4,color="black")+
geom_linerange(data=pred[c(8,11),],aes(ymin=Surrender[1],ymax=Surrender[2]),
size=2,color="orange")  +
#geom_text(data=pred[8,],aes(label="F12+\nF12:F22"),vjust=2,color="black") #+
geom_point(data=pred[pred$X==0,],color="black")
```





```{r}
g = glmer(Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1| Subject) , family = "binomial", data = pool_disagree, REML=F)


summary(g)

```






```{r}
#predict predicts new data (0 or 1s in your case) while fitted returns the probability of getting a one. To see this, try out fitted(m, summary = FALSE) and predict(m, summary = FALSE)

pool_long$Leader_gender <- as.factor(pool_long$Leader_gender)
pool_long$Follower_gender <- as.factor(pool_long$Follower_gender)

#make predictions

nd <- tibble(Surrender = factor(seq(from = 0, to = 1, by = 1)), Leader_gender = factor(seq(from = 0, to = 1, by = 1)), Follower_gender = factor(seq(from = 0, to = 1, by = 1)), skill_dif_correct = as.numeric(factor(seq(from = 0, to = 1, by = 1))))


#nd <- cbind(nd, "skill_dif_correct")

p <- predict(m_pool_correct, allow_new_levels = T, re_formula = ~ (1 + skill_dif_correct:Follower_gender| Subject), sample_new_levels = "gaussian", newdata = nd, summary = FALSE)

p_fit <- fitted(m_pool_correct, allow_new_levels = T, re_formula = ~ (1 + skill_dif_correct:Follower_gender| Subject), sample_new_levels = "gaussian", newdata = nd, summary = FALSE)

#as dataframe
p <- as.data.frame(p)
p_fit <- as.data.frame(p_fit)

#make dataframe with diagnosis and predicted estimates 
stick <- subset(p_fit, select = V1)

stick$surrender <- 0

names(stick) <- c("Estimate", "surrender")

surrender <- subset(p_fit, select = V2)

surrender$surrender <- 1

names(surrender) <- c("Estimate", "surrender")

pred_data <- rbind(stick, surrender)

pred_data$surrender <- as.factor(pred_data$surrender)

library(ggbeeswarm)
#create the plot
bee <- ggplot(pool_long, aes(x = surrender, y = skill_dif_correct)) +
  geom_violin(aes(x = surrender, y = Estimate), data = pred_data, trim = FALSE) + 
  ylim(-3,3) + 
  geom_quasirandom(alpha = 0.5, colour = "dark red") +
  labs(x = "diagnosis", y = "Pitch", title = "Flot plot") + 
  geom_boxplot(aes(x = surrender, y = Estimate), data = pred_data, width = 0.12) 

  
bee


dens(pred_data)
```



```{r}





ggplot(pool_disagree, aes(skill_dif_correct, Surrender, fill = Leader_gender, color = Follower_gender)) +
  geom_point() +
  stat_smooth(method.args=list(family="binomial"), se=FALSE)


ggplot(pool_disagree, aes(x=skill_dif_correct)) +
  geom_smooth( data= pool_disagree, aes(y=Surrender, ymin = 0, ymax = 1, fill = Leader_Follower, color = Leader_Follower))


ggplot(dat, aes(x=mpg, y=vs)) + geom_point() + 
  stat_smooth(method="glm", method.args=list(family="binomial"), se=FALSE)


library(rethinking)
dens(pool_disagree$skill_dif_correct)

dens(pool_disagree$skill_dif_answer)


pool_disagree$Surrender <- as.factor(pool_disagree$Surrender)
dens(pool_disagree$Surrender)


summary(m_pool_correct)
```





#frequentist
```{r}

no_pool_long$Surrender <- as.factor(no_pool_long$Surrender)

g = glmer(Surrender ~ skill_dif_correct*Leader_Follower + (1 | Subject) , family = "binomial", data = pool_disagree)


summary(g)

```


### From supervision

First we check whether skill difference has had any effect
Second we test hypotheses on our model

```{r}

prior_m1 <- c(
  prior(normal(0,1),class=intercept),
  prior(normal(0,.2),class=beta),
  prior(normal(0,.1),class=sd)
)

prior_m2 <- c(
  prior(normal(0,.2),class=beta),
  prior(normal(0,.1),class=sd)
)


# Model w skill difference
m1 <- brm(
  Surrender ~ skill_dif_correct * Leader_gender * Follower_gender + (1 + skill_dif_correct:Follower_gender | Subject ),
  data = no_pool_disagree,
  prior = prior_m1,
  sample_prior=T,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123, # Adding a seed makes results reproducible.
  cores=2,
  chains=2
  ) 

# Model w/o skill difference
m2 <- brm(
  Surrender ~ 0 + Leader_gender : Follower_gender + (0 + Follower_gender | Subject ),
  data = no_pool_disagree,
  prior = prior_m2,
  sample_prior=T,
  family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
  seed = 123, # Adding a seed makes results reproducible.
  chains=2,
  cores=2
  ) 

waic(m1,m2)

# Hypothesis testing

# H1: there is a leader effect: male leaders tend to surrender less than female leaders
hypothesis(m2, "(Leader_gender0:Follower_gender0 + Leader_gender0:Follower_gender1)/2 < (Leader_gender1:Follower_gender0 + Leader_gender1:Follower_gender1)/2")

# H2: there is a follower effect: leaders tend to surrender more to men than to women
hypothesis(m2, "(Leader_gender0:Follower_gender0 + Leader_gender1:Follower_gender0)/2 > (Leader_gender0:Follower_gender1 + Leader_gender1:Follower_gender1)/2")

# H3: there is an interaction: 
## males are more discriminative as to their followers gender than females are
hypothesis(m2, "(Leader_gender0:Follower_gender0 - Leader_gender0:Follower_gender1) > (Leader_gender1:Follower_gender0 - Leader_gender1:Follower_gender1)")

```


