---
title: "DataCleaning"
author: "Signe Kløve Kjær"
date: "2/5/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading packages, include = FALSE}

#install.packages("tidybayes"); install.packages("LaplacesDemon")
library(brms); library(tidyverse); library(tidybayes); library(ggplot2); library(LaplacesDemon); library(rethinking); library(tidyr); library(reshape2);library(pacman); library(tibble);library(tidyr)

```



```{r loading data and merging, include = FALSE}
setwd("~/Cognitive Science/4. Semester/Social and Cultural Dynamics Exam/SocKultExam-master/")

data_path = "Data/"

#lets loop
files <- list.files(path = data_path)
files

data <- data.frame(matrix(ncol = 36, nrow = 0))


for (i in files) {
  d <- read.delim(file = paste(data_path, i, sep = ""), sep = ",", header = TRUE)
  data = rbind(data,d)
}

#KIRIS DATA
kiri_path = "~/Cognitive Science/4. Semester/Social and Cultural Dynamics Exam/SocKultExam-master/"
kiri_files <- list.files(path = kiri_path, pattern = "*.csv")
kiri_files

kiri_data <- data.frame(matrix(ncol = 35, nrow = 0))
for (i in kiri_files) {
  d <- read.delim(file = paste(kiri_path, i, sep = ""), sep = ",", header = TRUE, stringsAsFactors = FALSE)
  kiri_data = rbind(kiri_data,d)
}


#merge the two

kiri_data <- add_column(kiri_data, Computer = "Two screens", .after = 4)

data <- rbind(data, kiri_data)

unique(data$GroupNumber)



```


```{r clean data, include = FALSE}

#CLEAN DATA

data <- subset(data, select = -c(X))

data$GroupNumber[data$GroupNumber == "17_10_30"] <- 17
data$GroupNumber[data$GroupNumber == "18_10_30"] <- 18
data$GroupNumber[data$GroupNumber == "19_10_50"] <- 19
data$GroupNumber[data$GroupNumber == "20_10_50"] <- 20
data$GroupNumber[data$GroupNumber == "21_12_15"] <- 21
data$GroupNumber[data$GroupNumber == "22_12_15"] <- 22
data$GroupNumber[data$GroupNumber == "23_12_40"] <- 23
data$GroupNumber[data$GroupNumber == "24_12_40"] <- 24
data$GroupNumber[data$GroupNumber == "25_15_00"] <- 25
data$GroupNumber[data$GroupNumber == "26_15_00"] <- 26
data$GroupNumber[data$GroupNumber == "27_15_20"] <- 27
data$GroupNumber[data$GroupNumber == "28_15_20"] <- 28
data$GroupNumber[data$GroupNumber == "29_16_00"] <- 29
data$GroupNumber[data$GroupNumber == "30_16_00"] <- 30
data$GroupNumber[data$GroupNumber == "31_16_20"] <- 31
data$GroupNumber[data$GroupNumber == "32_16_20"] <- 32
data$GroupNumber[data$GroupNumber == "33_9_30"] <- 33
data$GroupNumber[data$GroupNumber == "34_09_30"] <- 34
data$GroupNumber[data$GroupNumber == "35_09_50"] <- 35
data$GroupNumber[data$GroupNumber == "36_9_50"] <- 36
data$GroupNumber[data$GroupNumber == "37_26_4"] <- 37
data$GroupNumber[data$GroupNumber == "38_26_4"] <- 38
data$GroupNumber[data$GroupNumber == "39_26_4"] <- 39
data$GroupNumber[data$GroupNumber == "40_26_4"] <- 40

data$SubjectID_left <- as.character(data$SubjectID_left)
data$SubjectID_right <- as.character(data$SubjectID_right)
data$SubjectID_left[data$SubjectID_left == "steph"] <- "stephanie"
data$SubjectID_right[data$SubjectID_right == "Emil"] <- "emil"
data$SubjectID_right[data$SubjectID_right == "Sebber"] <- "seb"
data$SubjectID_left[data$SubjectID_left == "signe"] <- "SigneR"
data$SubjectID_right[data$SubjectID_right == "karo"] <- "Karoline"
data$SubjectID_right[data$SubjectID_right == "tobias"] <- "Toby"
data$SubjectID_left[data$SubjectID_left == "Nina"] <- "nina"
data$SubjectID_right[data$SubjectID_right == "theasmom"] <- "Theasmom"
data$SubjectID_left[data$SubjectID_left == "emma"] <- "Emma"
data$SubjectID_right[data$SubjectID_right == "LasseKob"] <- "Lasse"

```



```{r making variables for sensitivty, include = FALSE}
#Making column, which expresses difficulty
data$dif_blue <- data$Prop_blue_image_1-data$Prop_blue_image_2

#Making a column, which expresses answer of participants, 0 = left picture, 1 = right picture
data$right_answer <- ifelse(data$Response_right > 0, 1, 0)
data$left_answer <- ifelse(data$Response_left > 0, 1, 0)

#Joining joint answer to one column
data$joint_answer <- data$Joint_right+ data$Joint_left

```


Bayesian tutorial on logistic regression: https://www.jamesrrae.com/post/bayesian-logistic-regression-using-brms-part-1/

#Individual performance

```{r logistic regression using wide format, individual left}

###LEFT
#Making unique subjects
data$unique_ID_right <- paste(data$GroupNumber, data$SubjectID_right, sep = "_")
data$unique_ID_left <- paste(data$GroupNumber, data$SubjectID_left, sep = "_")

#Getting priors
get_prior(left_answer ~ dif_blue, data = data)

#Making a number of iterations variable
n = 1

###Making a loop for individual slope
for (i in unique(data$unique_ID_left)){
  data_i <- filter(data, unique_ID_left == i)
  
  #Defining priors
  prior =  c(
  prior(normal(0,2), class = "Intercept"), #How to motiavte this?
  #prior(normal(0,2), class = "sigma"), #Roughly on the same scale
  prior(normal(0,2), class = "b"), #How to motiavte this?
  prior(normal(0,1), class = "b", coef = "dif_blue"))
  
  #Prior predictive check
  prior_check <- brm( left_answer ~ dif_blue, prior = prior,
           data = data_i, sample_prior = "only",iter = 4000, family = "bernoulli")

  pp_check <- pp_check(prior_check, nsamples = 100)   
  
  #Saving pp_check, doesn't work. But probably not nessecary either...
  #ggsave(filename = paste("pp_check_prior/",plot_var[[n]], sep = ""), plot = pp_check, device = png)

 
  #Making the model
  m <- brm(
    left_answer ~ dif_blue,
    data = data_i,
    prior = prior,
    family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
    seed = 123 # Adding a seed makes results reproducible.
  ) 
  
  summary(m)
  
  #Saving summary in temporary dataframe
  data_i$Est_int_left <- fixef(m)[1]
  data_i$Error_int_left <- fixef(m)[3]
  data_i$Est_dif_blue_left <- fixef(m)[2]
  data_i$Error_dif_blue_left <- fixef(m)[4]
  
  #Insert into permanent data frame
  if (n == 1){
    Results <- data_i
  } else {
    Results <- rbind(Results, data_i)
  }
  
n = n + 1
  
}

```


```{r logistic regression using wide format, individual right}
#Making a number of iterations variable
n = 1

###Making a loop for individual slope
for (i in unique(data$unique_ID_right)){
  data_i <- filter(Results, unique_ID_right == i)
  
  #Defining priors
  prior =  c(
  prior(normal(0,2), class = "Intercept"), #How to motiavte this?
  #prior(normal(0,2), class = "sigma"), #Roughly on the same scale
  prior(normal(0,2), class = "b"), #How to motiavte this?
  prior(normal(0,1), class = "b", coef = "dif_blue"))
  
  #Prior predictive check
  prior_check <- brm( right_answer ~ dif_blue, prior = prior,
           data = data_i, sample_prior = "only",iter = 4000, family = "bernoulli")

  pp_check <- pp_check(prior_check, nsamples = 100)   
  
  #Saving pp_check, doesn't work. But probably not nessecary either...
  #ggsave(filename = paste("pp_check_prior/",plot_var[[n]], sep = ""), plot = pp_check, device = png)

 
  #Making the model
  m <- brm(
    right_answer ~ dif_blue,
    data = data_i,
    prior = prior,
    family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
    seed = 123 # Adding a seed makes results reproducible.
  ) 
  
  summary(m)
  
  #Saving summary in temporary dataframe
  data_i$Est_int_right <- fixef(m)[1]
  data_i$Error_int_right <- fixef(m)[3]
  data_i$Est_dif_blue_right <- fixef(m)[2]
  data_i$Error_dif_blue_right <- fixef(m)[4]
  
  #Insert into permanent data frame
  if (n == 1){
    Results <- data_i
  } else {
    Results <- rbind(Results, data_i)
  }
  
n = n + 1
  
}


```

#Joint performance

```{r logistic regression using wide format, joint}
###JOINT
#Recoding joint answer to be 0 and 1's, 0 right, 1 left, NA = no leader
Results$joint_answer[Results$joint_answer == 0] <- NA #Replacing 0's with NA
Results$joint_answer[Results$joint_answer == -1] <- 0

#Making a number of iterations variable
n = 1

###Making a loop for individual slope
for (i in unique(data$GroupNumber)){
  data_i <- filter(Results, GroupNumber == i)
  
  #Defining priors
  prior =  c(
  prior(normal(0,2), class = "Intercept"), #How to motiavte this?
  #prior(normal(0,2), class = "sigma"), #Roughly on the same scale
  prior(normal(0,2), class = "b"), #How to motiavte this?
  prior(normal(0,1), class = "b", coef = "dif_blue"))
  
  #Prior predictive check
  prior_check <- brm( joint_answer ~ dif_blue, prior = prior,
           data = data_i, sample_prior = "only",iter = 4000, family = "bernoulli")

  pp_check <- pp_check(prior_check, nsamples = 100)   
  
  #Saving pp_check, doesn't work. But probably not nessecary either...
  #ggsave(filename = paste("pp_check_prior/",plot_var[[n]], sep = ""), plot = pp_check, device = png)

 
  #Making the model
  m <- brm(
    joint_answer ~ dif_blue,
    data = data_i,
    prior = prior,
    family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
    seed = 123 # Adding a seed makes results reproducible.
  ) 
  
  summary(m)
  
  #Saving summary in temporary dataframe
  data_i$Est_int_joint <- fixef(m)[1]
  data_i$Error_int_joint <- fixef(m)[3]
  data_i$Est_dif_blue_joint <- fixef(m)[2]
  data_i$Error_dif_blue_joint <- fixef(m)[4]
  
  #Insert into permanent data frame
  if (n == 1){
    Results <- data_i
  } else {
    Results <- rbind(Results, data_i)
  }
  
n = n + 1
  
}


#The outcome is in log odds scale, we can use tidybayes to transform them 

#parameters <- m1 %>% gather_draws(b_dif_blue) %>% median_hdi()
#  print(exp(parameters[c(".value",".lower",".upper")])) # exp() converts log-odds to odds


```

#Making long format
This is in order to calculate the equality bias 

```{r making long format, include = FALSE}
#take just the columns we need
#L_data <- subset(Results, select = c(GroupNumber, SubjectID_right, SubjectID_left, Gender_left, Gender_right, Familiarity, dif_blue, left_answer, right_answer, joint_answer ))


#change to long format 

L_data <- melt(Results, 
                     variable.name = "Position",
                     value.name = "Subject",
                     id.vars = c("GroupNumber", "Gender_left", "Gender_right", "Familiarity", "dif_blue", "left_answer", "right_answer", "joint_answer"))

```

##Følgende blev ikke nødvendigt alligevel...
```{r logistic regression using long format, individual}

##Checking correlation between regression variables
#This will help us know what to expect before doing our logistic regression analysis
cor.test(sen_data$answer,sen_data$dif_blue )
cor.test(sen_data$joint_answer,sen_data$dif_blue)

#They are negatively correlated, BUT WHAT DOES THIS MEAN?

#Making unique subjects
sen_data$unique_ID <- paste(sen_data$GroupNumber, sen_data$Subject, sep = "_")

#Getting priors
get_prior(answer ~ dif_blue, data = sen_data)

#Making a list varibale for saving summary
summary_var <- paste("summary", unique(sen_data$unique_ID), sep = "_")

#Making variable list for saving plots
plot_var <- paste("prior_check", unique(sen_data$unique_ID), sep = "_")

#Making a number of iterations variable
n = 1

###Making a loop for individual slope
for (i in unique(sen_data$unique_ID)){
  data_i <- filter(sen_data, unique_ID == i)
  
  #Defining priors
  prior =  c(
  prior(normal(0,2), class = "Intercept"), #How to motiavte this?
  #prior(normal(0,2), class = "sigma"), #Roughly on the same scale
  prior(normal(0,2), class = "b"), #How to motiavte this?
  prior(normal(0,1), class = "b", coef = "dif_blue"))
  
  #Prior predictive check
  prior_check <- brm( answer ~ dif_blue, prior = prior,
           data = data_i, sample_prior = "only",iter = 4000, family = "bernoulli")

  pp_check <- pp_check(prior_check, nsamples = 100)   
  
  #Saving pp_check, doesn't work. But probably not nessecary either...
  #ggsave(filename = paste("pp_check_prior/",plot_var[[n]], sep = ""), plot = pp_check, device = png)

 
  #Making the model
  m <- brm(
    answer ~ dif_blue,
    data = data_i,
    prior = prior,
    family = "bernoulli", #As we had a binary outcome, we set this to "bernoulli"
    seed = 123 # Adding a seed makes results reproducible.
  ) 
  
  summary(m)
  
  #Saving summary in temporary dataframe
  data_i$Est_int <- fixef(m)[1]
  data_i$Error_int <- fixef(m)[3]
  data_i$Est_dif_blue <- fixef(m)[2]
  data_i$Error_dif_blue <- fixef(m)[4]
  
  #Insert into permanent data frame
  if (n == 1){
    Results_individual <- data_i
  } else {
    Results_individual <- rbind(Results_individual, data_i)
  }
  
n = n + 1
  
}


#The outcome is in log odds scale, we can use tidybayes to transform them 

#parameters <- m1 %>% gather_draws(b_dif_blue) %>% median_hdi()
#  print(exp(parameters[c(".value",".lower",".upper")])) # exp() converts log-odds to odds


```
