---
title: "simulation"
author: "Thea Rolskov Sloth"
date: "14/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/4. SEMESTER/Social and cultural dynamics/exam/script")

library(pacman)
p_load(strsplit, qdapTools, stringr)
```


```{r}

setwd("/Users/signeklovekjaer/Documents/CognitiveScience/4.semester/Social_and_cultural_dynamics_in_cognition/Exam/SocKultExam/Simulation_data/")

#lets loop
sim_files <- list.files(path = sim_path)
sim_files

sim_data <- as.data.frame(matrix(ncol = 16, nrow = 0))


for (i in sim_files) {
  s <- read.csv(i, stringsAsFactors = F)
  s$Results <- strsplit(s$Results, ",")
  
  ss <- list2df(s$Results, col1 = "X1", col2 = "X2")
  ss <- subset(ss, select = -c(X2))
  ss <- t(ss)
  
  ss <- gsub("\\[|\\]", "", ss)
  
  ss <- data.frame(ss, stringsAsFactors = F)
  names(ss) <- c("male_level1", "male_level2", "male_level3", "male_level4", "male_level5", "male_level6", "male_level7", "male_level8","female_level1", "female_level2", "female_level3", "female_level4", "female_level5", "female_level6", "female_level7", "female_level8")
  
  ss$male_level8 <- round(as.numeric(ss$male_level8), digits = 2)
  ss$male_level7 <- round(as.numeric(ss$male_level7), digits = 2)
  ss$male_level6 <- round(as.numeric(ss$male_level6), digits = 2)
  ss$male_level5 <- round(as.numeric(ss$male_level5), digits = 2)
  ss$male_level4 <- round(as.numeric(ss$male_level4), digits = 2)
  ss$male_level3 <- round(as.numeric(ss$male_level3), digits = 2)
  ss$male_level2 <- round(as.numeric(ss$male_level2), digits = 2)
  ss$male_level1 <- round(as.numeric(ss$male_level1), digits = 2)
  
  ss$female_level8 <- round(as.numeric(ss$female_level8), digits = 2)
  ss$female_level7 <- round(as.numeric(ss$female_level7), digits = 2)
  ss$female_level6 <- round(as.numeric(ss$female_level6), digits = 2)
  ss$female_level5 <- round(as.numeric(ss$female_level5), digits = 2)
  ss$female_level4 <- round(as.numeric(ss$female_level4), digits = 2)
  ss$female_level3 <- round(as.numeric(ss$female_level3), digits = 2)
  ss$female_level2 <- round(as.numeric(ss$female_level2), digits = 2)
  ss$female_level1 <- round(as.numeric(ss$female_level1), digits = 2)
  
  ss$h = str_extract_all(i, "\\d")
  sim_data = rbind(sim_data,ss)
  
}


sim_data$total_women <- (sim_data[9]+sim_data[10]+sim_data[11]+sim_data[12]+sim_data[13]+sim_data[14]+sim_data[15]+sim_data[16])/8 



sim_data$total_men <- (sim_data[1]+sim_data[2]+sim_data[3]+sim_data[4]+sim_data[5]+sim_data[6]+sim_data[7]+sim_data[8])/8 

men <- sim_data$total_men

women <- sim_data$total_women

women <- as.data.frame(women)

names(women) <- c("percentage")

women$gender <- "women"

sim_data_long <- data.frame(matrix(ncol = 2, nrow = 0))


sim_data_long <- c(men) 

names(sim_data_long) <- c("percentage")

sim_data_long$gender <- "men"

sim_data_long <- as.data.frame(sim_data_long)

sim_data_long <- rbind(sim_data_long, women)

sim_data_long$year <- rep(1:5, 2)

```


```{r}
#plot it 

p4 <- ggplot() + theme_bw() +
  geom_bar(aes(y = percentage, x = year, fill = gender), data = sim_data_long, stat="identity") +
  geom_text(data=sim_data_long, aes(x = year, y = pos, label = paste0(percentage,"%")), size=4) +
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title = element_blank()) +
  scale_x_continuous(breaks=seq(2006,2014,1)) +
  scale_y_continuous(labels = dollar_format(suffix = "%", prefix = "")) +
  labs(x="Year", y="Percentage") +
  ggtitle("Composition of Exports to China (%)")
p4


```




